(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "sc" "http://joseito.republika.pl/sunrise-commander/")

(depends-on "ac-nrepl")
(depends-on "ace-jump-mode")
(depends-on "ack-and-a-half")
(depends-on "auctex")
(depends-on "auto-complete")
(depends-on "autopair")
(depends-on "clojure-mode")
(depends-on "ctags")
(depends-on "deferred")
(depends-on "elpy")
(depends-on "emacs-eclim")
(depends-on "etags-select")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "haskell-mode")
(depends-on "ido-ubiquitous")
(depends-on "jedi")
(depends-on "magit")
(depends-on "nav")
(depends-on "nrepl")
(depends-on "nrepl-ritz")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "pony-mode")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "rbenv")
(depends-on "rinari")
(depends-on "robe")
(depends-on "ruby-end")
(depends-on "scala-mode2")
(depends-on "session")
(depends-on "smex")
(depends-on "twittering-mode")
(depends-on "use-package")
(depends-on "yasnippet")
(depends-on "zenburn-theme")